resolver: lts-14.13

packages:
- shared
- gui
- api

extra-deps:
- aeson-injector-1.1.2.0
- raven-haskell-0.1.2.1
- jsaddle-0.9.6.0
- jsaddle-warp-0.9.6.0
- jsaddle-dom-0.9.3.2
- ref-tf-0.4.0.2
- git: https://github.com/tvh/hasql-migration
  commit: 58c90f7c5c0e829708c35db9d2c8bc47e86621eb
- git: https://github.com/DoctorRyner/miso-spa
  commit: 8553fe0f789960f2f41950520a12f333c7b22493
- git: https://github.com/DoctorRyner/miso-styled
  commit: 41b8627d4cfeb50c1d50cb2dc7d64cc44ef35cf4
- git: https://github.com/DoctorRyner/miso-http
  commit: ca7d070fabb1656137c4abe9d2d7234ca605bdf5

flags:
  miso:
    jsaddle: true
