name:                gui

dependencies:
- base >= 4.7 && < 5
- shared
- text
- generic-lens
- miso
- miso-spa
- miso-http
- miso-styled

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Werror=incomplete-patterns

default-extensions:
- DeriveGeneric
- DuplicateRecordFields
- OverloadedLabels
- OverloadedStrings
- LambdaCase

library:
  source-dirs: src

executables:
  gui-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
    - condition: impl(ghcjs)
      then:
        ghc-options:
        - -dedupe
      else:
        ghc-options: []
    dependencies:
    - gui
