name:                api

dependencies:
- base >= 4.7 && < 5
- shared
- text
- bytestring
- generic-lens
- servant
- servant-server
- servant-swagger
- servant-swagger-ui
- swagger2
- aeson
- aeson-injector
- warp
- wai
- wai-cors
- wai-logger
- transformers
- yaml
- hasql
- hasql-pool
- postgresql-simple
- postgresql-simple-migration
- time
- miso

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-unused-do-bind
- -Werror=incomplete-patterns

default-extensions:
- DeriveGeneric
- DuplicateRecordFields
- OverloadedLabels
- OverloadedStrings
- LambdaCase
- DataKinds
- TypeOperators

library:
  source-dirs: src

executables:
  api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api
